# Generated by Django 5.2.8 on 2025-11-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('search_placeholder_1', models.CharField(default='Where do you want to go?', max_length=255)),
                ('search_placeholder_2', models.CharField(default='Dates / flexible', max_length=255)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
