# Generated by Django 5.2.8 on 2025-12-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.CharField(default='#', max_length=255)),
                ('background_image', models.ImageField(upload_to='call_section/')),
            ],
            options={
                'verbose_name': 'Call Section',
                'verbose_name_plural': 'Call Section',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('price_text', models.CharField(max_length=100)),
                ('icon_class', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deals/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('person_type', models.CharField(max_length=50)),
                ('url', models.CharField(default='#', max_length=255)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ribbon_text', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('country_category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price_text', models.CharField(max_length=255)),
                ('open_text', models.CharField(max_length=50)),
                ('reviews_text', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='FooterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Footer Category',
                'verbose_name_plural': 'Footer Categories',
            },
        ),
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Footer Contact',
                'verbose_name_plural': 'Footer Contact',
            },
        ),
        migrations.CreateModel(
            name='FooterQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Footer Quick Link',
                'verbose_name_plural': 'Footer Quick Links',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('search_placeholder_1', models.CharField(default='Where do you want to go?', max_length=255)),
                ('search_placeholder_2', models.CharField(default='Dates / flexible', max_length=255)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='MiddleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(blank=True, max_length=255, null=True)),
                ('main_title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.CharField(default='#', max_length=255)),
                ('background_image', models.ImageField(upload_to='middle_banner/')),
            ],
            options={
                'verbose_name': 'Middle Banner',
                'verbose_name_plural': 'Middle Banner',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('icon_class', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
    ]
