# Generated by Django 5.2.8 on 2025-11-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ribbon_text', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('country_category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price_text', models.CharField(max_length=255)),
                ('open_text', models.CharField(max_length=50)),
                ('reviews_text', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('url', models.URLField(default='#')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
    ]
