# Generated by Django 5.2.8 on 2025-11-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_destination_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(blank=True, max_length=255, null=True)),
                ('main_title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.CharField(default='#', max_length=255)),
                ('background_image', models.ImageField(upload_to='middle_banner/')),
            ],
            options={
                'verbose_name': 'Middle Banner',
                'verbose_name_plural': 'Middle Banner',
            },
        ),
    ]
