# Generated by Django 5.2.8 on 2025-12-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vendor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='phone',
        ),
    ]
