# Generated by Django 5.2.8 on 2025-11-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_middlebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deals/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('person_type', models.CharField(max_length=50)),
                ('url', models.CharField(default='#', max_length=255)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
            },
        ),
    ]
