# Generated by Django 5.2.8 on 2025-11-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.CharField(default='#', max_length=255)),
                ('background_image', models.ImageField(upload_to='call_section/')),
            ],
            options={
                'verbose_name': 'Call Section',
                'verbose_name_plural': 'Call Section',
            },
        ),
    ]
