# Generated by Django 5.2.8 on 2025-12-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blogcategory_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Contact TravelBiz', max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('help_center_title', models.CharField(default='Help Center', max_length=255)),
                ('help_center_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('help_center_email', models.CharField(blank=True, max_length=100, null=True)),
                ('address_title', models.CharField(default='Address', max_length=255)),
                ('address_text', models.CharField(blank=True, max_length=255, null=True)),
                ('business_title', models.CharField(default='Business Queries', max_length=255)),
                ('business_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('business_email', models.CharField(blank=True, max_length=100, null=True)),
                ('map_embed_url', models.TextField(blank=True, help_text='Paste the Google Maps Embed URL here', null=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
    ]
