# Generated by Django 5.2.8 on 2025-12-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='wishlist/')),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField()),
                ('review_text', models.CharField(max_length=200)),
            ],
        ),
    ]
