# Generated by Django 5.2.8 on 2025-11-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Footer Quick Link',
                'verbose_name_plural': 'Footer Quick Links',
            },
        ),
    ]
