# Generated by Django 5.2.8 on 2025-12-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='wishlist_banner/')),
            ],
        ),
    ]
