# Generated by Django 5.2.8 on 2025-11-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_footerquicklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Footer Category',
                'verbose_name_plural': 'Footer Categories',
            },
        ),
    ]
