# Generated by Django 5.2.8 on 2025-12-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_wishlistbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Surat', 'Surat'), ('Ahmedabad', 'Ahmedabad'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai')], max_length=50)),
                ('vehicle', models.CharField(max_length=50)),
                ('how_hear', models.TextField()),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
