# Generated by Django 5.2.8 on 2025-12-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_riderapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Surat', 'Surat'), ('Ahmedabad', 'Ahmedabad'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai')], max_length=50)),
                ('service_area', models.CharField(blank=True, max_length=255)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('airport_experience', models.CharField(blank=True, max_length=10)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('driving_license', models.FileField(upload_to='drivers/licenses/')),
                ('vehicle_rc', models.FileField(upload_to='drivers/rc/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='drivers/id/')),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='drivers/vehicle/')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RiderApplication',
        ),
    ]
