# Generated by Django 5.2.8 on 2026-01-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_driverapplication_delete_riderapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='background_image',
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_video',
            field=models.FileField(blank=True, help_text='Upload MP4 video (recommended <15MB)', null=True, upload_to='hero/videos/'),
        ),
    ]
