# Generated by Django 5.2.8 on 2026-07-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_herosection_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('meta_title', models.CharField(help_text='SEO Title (Max 60–70 chars)', max_length=70)),
                ('meta_description', models.TextField(help_text='SEO Description (Max 150–160 chars)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=70)),
                ('og_description', models.TextField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={},
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='background_video',
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_video_url',
            field=models.URLField(blank=True, help_text='Paste Dailymotion video URL (e.g. https://www.dailymotion.com/video/xxxx)', null=True),
        ),
    ]
