"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9ct#xnnvp*#09#*=4g+h@j&tf-m!$-l5911(zm_1v7@bn=w1#l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main', 
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


JAZZMIN_SETTINGS = {
    "site_title": "TravelBiz Admin",
    "site_header": "TravelBiz",
    "site_brand": "TravelBiz Admin Panel",
    # "site_logo": "img/logon.png",
    "site_logo_classes": "img-fluid",
    "site_logo_width": 150, 
    "welcome_sign": "Welcome to TravelBiz Dashboard",
    "copyright": "TravelBiz",

    # Top search models
    "search_model": [
        "main.Hero",
        "main.Destination",
        "main.Categories",
        "main.Deals",
    ],

    # Sidebar Menu Order
    "order_with_respect_to": [
    "main.HeroSection",
    "main.MiddleBanner",
    "main.CallSection",

    "main.Categories",
    "main.Destinations",
    "main.Deals",

    "main.FooterContact",
    "main.FooterCategories",
    "main.FooterQuickLinks",
    "main.SocialLinks",
],


    # Icons
    "icons": {
    "auth.User": "fas fa-user",
    "auth.Group": "fas fa-users",

    "main.HeroSection": "fas fa-image",
    "main.MiddleBanner": "fas fa-ad",
    "main.CallSection": "fas fa-phone",

    "main.Categories": "fas fa-tags",
    "main.Destinations": "fas fa-map-marker-alt",
    "main.Deals": "fas fa-percent",

    "main.FooterContact": "fas fa-address-book",
    "main.FooterCategories": "fas fa-list",
    "main.FooterQuickLinks": "fas fa-link",
    "main.SocialLinks": "fas fa-share-alt",
},


    # UI Builder (optional)
    "show_ui_builder": False,
}




WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


AUTH_USER_MODEL = "accounts.User"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
